### ISSUE TITLE
pip install fails if requests is not already installed

### ISSUE THREAD

**Issue by mriedem** [qiskit-community/Quantum-Challenge-Grader#6]
There seems to be a chicken-and-egg issue with installing this package because the setup.py pulls the version from an imported module which eventually imports some other modules that require `requests` which is a dependency for this package, and if not already installed results in a pip install failure:

```
$ pip install ./Quantum-Challenge-Grader-main
Processing ./Quantum-Challenge-Grader-main
    ERROR: Command errored out with exit status 1:
     command: /home/osboxes/ibmq/ibmq-jupyterhub-user-image/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-w1l3q3t7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-w1l3q3t7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hwix9f_m                                                                                                                           
         cwd: /tmp/pip-req-build-w1l3q3t7/                                                                                                                                                   
    Complete output (11 lines):                                                                                                                                                              
    Traceback (most recent call last):                                                                                                                                                       
      File "<string>", line 1, in <module>                                                                                                                                                   
      File "/tmp/pip-req-build-w1l3q3t7/setup.py", line 7, in <module>                                                                                                                       
        from qc_grader import __version__                                                                                                                                                    
      File "/tmp/pip-req-build-w1l3q3t7/qc_grader/__init__.py", line 11, in <module>                                                                                                         
        from qc_grader.exercises.qc import *                                                                                                                                                 
      File "/tmp/pip-req-build-w1l3q3t7/qc_grader/exercises/__init__.py", line 3, in <module>                                                                                                
        from ..api import get_challenge_question_set                                                                                                                                         
      File "/tmp/pip-req-build-w1l3q3t7/qc_grader/api.py", line 2, in <module>                                                                                                               
        import requests                                                                                                                                                                      
    ModuleNotFoundError: No module named 'requests'
```

Not a huge deal, just something I noticed.

**Comment by mriedem** [comment]
If I manually install `requests` then I run into the same problem with `qiskit`:

```
$ pip install ./Quantum-Challenge-Grader-main
Processing ./Quantum-Challenge-Grader-main
    ERROR: Command errored out with exit status 1:
     command: /home/osboxes/ibmq/ibmq-jupyterhub-user-image/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hi_c2d1h/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hi_c2d1h/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ix63icp4                                                                                                                           
         cwd: /tmp/pip-req-build-hi_c2d1h/                                                                                                                                                   
    Complete output (11 lines):                                                                                                                                                              
    Traceback (most recent call last):                                                                                                                                                       
      File "<string>", line 1, in <module>                                                                                                                                                   
      File "/tmp/pip-req-build-hi_c2d1h/setup.py", line 7, in <module>                                                                                                                       
        from qc_grader import __version__                                                                                                                                                    
      File "/tmp/pip-req-build-hi_c2d1h/qc_grader/__init__.py", line 11, in <module>                                                                                                         
        from qc_grader.exercises.qc import *                                                                                                                                                 
      File "/tmp/pip-req-build-hi_c2d1h/qc_grader/exercises/qc/__init__.py", line 1, in <module>                                                                                             
        from .exercise1 import (                                                                                                                                                             
      File "/tmp/pip-req-build-hi_c2d1h/qc_grader/exercises/qc/exercise1.py", line 2, in <module>                                                                                            
        from qiskit import QuantumCircuit                                                                                                                                                    
    ModuleNotFoundError: No module named 'qiskit' 
```

**Comment by vabarbosa** [comment]
thanks. this has resolved by changing the way `setup.py` obtains the version
https://github.com/qiskit-community/Quantum-Challenge-Grader/commit/f8b674972ccedad2702409c8ea327d8b385cd1b9
